[LightMode]
# 覆盖默认值
OverrideDefault=True
# 高亮颜色
HighlightColor=#4fae7b
# 悬停时高亮颜色
HighlightHoverColor=#00007f
# 高亮文本颜色
HighlightTextColor=#ffffff
# 按下时高亮文本颜色
HighlightTextPressColor=#7f7f7f
# 高亮标签颜色
HighlightLabelColor=#ffffff
# 高亮注释颜色
HighlightCommentColor=#ffffff
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#ffffff
# 文本颜色
TextColor=#000000
# 标签颜色
LabelColor=#000000
# 注释颜色
CommentColor=#000000
# 翻页按钮颜色
PagingButtonColor=#000000
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#7f7f7f
# 指示文本颜色
AuxColor=#000000
# 光标前的预编辑颜色
PreeditColorPreCaret=#000000
# 预编辑光标颜色
PreeditColorCaret=#000000
# 光标后的预编辑颜色
PreeditColorPostCaret=#000000
# 边框颜色
BorderColor=#efefef32
# 分隔线颜色
DividerColor=#efefef

[DarkMode]
# 覆盖默认值
OverrideDefault=True
# 与浅色模式相同
SameWithLightMode=False
# 高亮颜色
HighlightColor=#21cfa3
# 悬停时高亮颜色
HighlightHoverColor=#00007f
# 高亮文本颜色
HighlightTextColor=#ffffff
# 按下时高亮文本颜色
HighlightTextPressColor=#7f7f7f
# 高亮标签颜色
HighlightLabelColor=#ffffff
# 高亮注释颜色
HighlightCommentColor=#ffffff
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#424242
# 文本颜色
TextColor=#ffffff
# 标签颜色
LabelColor=#ffffff
# 注释颜色
CommentColor=#ffffff
# 翻页按钮颜色
PagingButtonColor=#ffffff
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#7f7f7f
# 指示文本颜色
AuxColor=#ffffff
# 光标前的预编辑颜色
PreeditColorPreCaret=#ffffff
# 预编辑光标颜色
PreeditColorCaret=#ffffff
# 光标后的预编辑颜色
PreeditColorPostCaret=#ffffff
# 边框颜色
BorderColor=#ffffff32
# 分隔线颜色
DividerColor=#424242

[Typography]
# 布局
Layout=Vertical
# 书写模式
WritingMode="Horizontal top-bottom"
# 输入法感知版式
TypographyAwarenessForIM=True
# 翻页按钮样式
PagingButtonsStyle=Triangle

[Background]
# 图片
ImageUrl=
# 模糊
Blur=True
# 阴影
Shadow=True

[Font]
# 文本字号
TextFontSize=16
# 标签字号
LabelFontSize=12
# 注释字号
CommentFontSize=12
# 预编辑字号
PreeditFontSize=16

[Font/TextFontFamily]
0=

[Font/LabelFontFamily]
0=

[Font/CommentFontFamily]
0=986WB
1=通用字根

[Font/PreeditFontFamily]
0=

[Caret]
# 样式
Style=Blink
# 文本
Text=‸

[Highlight]
# 标记样式
MarkStyle=Text
# 标记文本
MarkText=🐧
# 悬停行为
HoverBehavior=None

[Size]
# 边框宽度（px）
BorderWidth=0
# 边框半径（px）
BorderRadius=6
# 外边距（px）
Margin=3
# 高亮半径（px）
HighlightRadius=3
# 顶填充（px）
TopPadding=6
# 右填充（px）
RightPadding=5
# 底填充（px）
BottomPadding=5
# 左填充（px）
LeftPadding=5
# 标签、文本、注释间隔（px）
LabelTextGap=5
# 垂直时最小宽度（px）
VerticalMinWidth=100
# 卷轴单元格宽度 (px)
ScrollCellWidth=65
# 水平分隔线宽度（px）
HorizontalDividerWidth=1

